---
engines:
  duplication:
    enabled: true
    checks:
      Simiar code:
        enabled: false
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
  - spec/
  - lib/_wavefront
