---

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-performance

Layout/LineLength:
  Max: 80
Metrics/ClassLength:
  Max: 150
Style/StringConcatenation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
