---

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/ClassLength:
  Max: 150

# Is nothing sacred?
Layout/LineLength:
  Max: 80

Style/StringConcatenation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
