---
AllCops:
  TargetRubyVersion: 2.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 13
