# Offense count: 64
Metrics/AbcSize:
  Max: 64

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 279

# Offense count: 46
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 39
